### PR TITLE
Make `annotations` a TaskKey, not a SettingKey

### LINKED ISSUE #125: [Proposal] the `annotations` should be a TaskKey and not a SettingKey
Hi,

Due to the fact that the `annotations` is a `SettingKey` and `appName` is a `TaskKey`, I can't write this:

```
annotations := Map(
  s"ad.datadoghq.com/${appName.value}.check_names"  -> Json.arr(JsString("jmx")).toString(),
  s"ad.datadoghq.com/${appName.value}.init_configs" -> "[{}]",
  s"ad.datadoghq.com/${appName.value}.instances"    -> Json.arr(Json.obj("host" -> "%%host%%", "port" -> 7199)).toString()
)
```

(See Datadog doc: https://docs.datadoghq.com/agent/autodiscovery/#template-source-kubernetes-pod-annotations)

A solution could be to change `annotations` to a `TaskKey`.
Another solution could be to change `appName` to a `SettingKey`

What's your opinion about that ?

### PR DESCRIPTION
**Pull request by guizmaii**
Fix #125

### CODE REVIEW

**Comment by dwijnand** [comment]
Thanks @guizmaii! 😁

**Comment by guizmaii** [comment]
Thanks Dale !

Is it possible for you to publish a new version ?

**Comment by dwijnand** [comment]
Hey @guizmaii.

Sure. As soon as there are fresh cuts of akka-management and reactive-lib we'll cut a release of sbt-reactive-app to include this change and the upstream updates.

**Comment by guizmaii** [comment]
Why not just publish a `v1.3.1` of this lib ?

**Pull request merged**
